apiVersion: v1
kind: ContinuousQuery
name: behind-pace
spec:
  mode: query
  sources:
    subscriptions:
      - id: stepup
        nodes:
          - sourceLabel: participants
          - sourceLabel: step_logs
          - sourceLabel: challenge_state
    joins:
      - id: HAS_LOG
        keys:
          - label: participants
            property: id
          - label: step_logs
            property: participant_id
      - id: IN_CHALLENGE
        keys:
          - label: participants
            property: challenge
          - label: challenge_state
            property: id
  query: >
    MATCH
      (c:challenge_state)<-[:IN_CHALLENGE]-(p:participants)-[:HAS_LOG]->(s:step_logs)
    WITH
      p, c.cumulative_target AS target, sum(s.steps) AS total
    WHERE
      total < target
    RETURN
      p.id AS id, p.name AS name, total, target