apiVersion: v1 
kind: ContinuousQuery
name: all-participants
spec:
  mode: query
  sources:
    subscriptions:
      - id: stepup
  query: >
    MATCH (p:participants)
    RETURN p.id AS id, p.name AS name, p.team AS team, p.target AS target
---
apiVersion: v1
kind: Reaction
name: debug
spec:
  kind: Debug
  queries:
    all-participants: