apiVersion: v1 
kind: Source
name: stepup
spec:
  kind: PostgreSQL
  properties:
    host: postgres.default.svc.cluster.local
    port: 5432
    user: drasi
    password: drasi
    database: stepup
    ssl: false
    tables:
      - public.participants
      - public.step_logs
      - public.daily_targets
      - public.challenge_state